"""Canonical constants for Scripture-book classification and ordering."""

DEUTEROCANONICAL_BOOKS = {
    "Tob",
    "Jdt",
    "Wis",
    "Sir",
    "Bar",
    "EpJer",
    "PrAzar",
    "Sus",
    "Bel",
    "1Macc",
    "2Macc",
    "1Esd",
    "2Esd",
    "PrMan",
    "AddEsth",
    "AddDan",
}

NEW_TESTAMENT_BOOKS = {
    "Matt",
    "Mark",
    "Luke",
    "John",
    "Acts",
    "Rom",
    "1Cor",
    "2Cor",
    "Gal",
    "Eph",
    "Phil",
    "Col",
    "1Thess",
    "2Thess",
    "1Tim",
    "2Tim",
    "Titus",
    "Phlm",
    "Heb",
    "Jas",
    "1Pet",
    "2Pet",
    "1John",
    "2John",
    "3John",
    "Jude",
    "Rev",
}

CANONICAL_BOOK_ORDER = [
    "Gen",
    "Exod",
    "Lev",
    "Num",
    "Deut",
    "Josh",
    "Judg",
    "Ruth",
    "1Sam",
    "2Sam",
    "1Kgs",
    "2Kgs",
    "1Chr",
    "2Chr",
    "Ezra",
    "Neh",
    "Tob",
    "Jdt",
    "Esth",
    "AddEsth",
    "1Macc",
    "2Macc",
    "Job",
    "Ps",
    "Prov",
    "Eccl",
    "Song",
    "Wis",
    "Sir",
    "Isa",
    "Jer",
    "Lam",
    "Bar",
    "EpJer",
    "Ezek",
    "Dan",
    "AddDan",
    "PrAzar",
    "Sus",
    "Bel",
    "Hos",
    "Joel",
    "Amos",
    "Obad",
    "Jonah",
    "Mic",
    "Nah",
    "Hab",
    "Zeph",
    "Hag",
    "Zech",
    "Mal",
    "Matt",
    "Mark",
    "Luke",
    "John",
    "Acts",
    "Rom",
    "1Cor",
    "2Cor",
    "Gal",
    "Eph",
    "Phil",
    "Col",
    "1Thess",
    "2Thess",
    "1Tim",
    "2Tim",
    "Titus",
    "Phlm",
    "Heb",
    "Jas",
    "1Pet",
    "2Pet",
    "1John",
    "2John",
    "3John",
    "Jude",
    "Rev",
]

KNOWN_BOOK_IDS = set(CANONICAL_BOOK_ORDER)

# Human-readable display names for OSIS book codes.
BOOK_DISPLAY_NAMES: dict[str, str] = {
    "Gen": "Genesis",
    "Exod": "Exodus",
    "Lev": "Leviticus",
    "Num": "Numbers",
    "Deut": "Deuteronomy",
    "Josh": "Joshua",
    "Judg": "Judges",
    "Ruth": "Ruth",
    "1Sam": "1 Samuel",
    "2Sam": "2 Samuel",
    "1Kgs": "1 Kings",
    "2Kgs": "2 Kings",
    "1Chr": "1 Chronicles",
    "2Chr": "2 Chronicles",
    "Ezra": "Ezra",
    "Neh": "Nehemiah",
    "Esth": "Esther",
    "Job": "Job",
    "Ps": "Psalms",
    "Prov": "Proverbs",
    "Eccl": "Ecclesiastes",
    "Song": "Song of Solomon",
    "Isa": "Isaiah",
    "Jer": "Jeremiah",
    "Lam": "Lamentations",
    "Ezek": "Ezekiel",
    "Dan": "Daniel",
    "Hos": "Hosea",
    "Joel": "Joel",
    "Amos": "Amos",
    "Obad": "Obadiah",
    "Jonah": "Jonah",
    "Mic": "Micah",
    "Nah": "Nahum",
    "Hab": "Habakkuk",
    "Zeph": "Zephaniah",
    "Hag": "Haggai",
    "Zech": "Zechariah",
    "Mal": "Malachi",
    "Matt": "Matthew",
    "Mark": "Mark",
    "Luke": "Luke",
    "John": "John",
    "Acts": "Acts",
    "Rom": "Romans",
    "1Cor": "1 Corinthians",
    "2Cor": "2 Corinthians",
    "Gal": "Galatians",
    "Eph": "Ephesians",
    "Phil": "Philippians",
    "Col": "Colossians",
    "1Thess": "1 Thessalonians",
    "2Thess": "2 Thessalonians",
    "1Tim": "1 Timothy",
    "2Tim": "2 Timothy",
    "Titus": "Titus",
    "Phlm": "Philemon",
    "Heb": "Hebrews",
    "Jas": "James",
    "1Pet": "1 Peter",
    "2Pet": "2 Peter",
    "1John": "1 John",
    "2John": "2 John",
    "3John": "3 John",
    "Jude": "Jude",
    "Rev": "Revelation",
    # Deuterocanonical
    "Tob": "Tobit",
    "Jdt": "Judith",
    "AddEsth": "Additions to Esther",
    "1Macc": "1 Maccabees",
    "2Macc": "2 Maccabees",
    "Wis": "Wisdom of Solomon",
    "Sir": "Sirach",
    "Bar": "Baruch",
    "EpJer": "Epistle of Jeremiah",
    "AddDan": "Additions to Daniel",
    "PrAzar": "Prayer of Azariah",
    "Sus": "Susanna",
    "Bel": "Bel and the Dragon",
    "1Esd": "1 Esdras",
    "2Esd": "2 Esdras",
    "PrMan": "Prayer of Manasseh",
}

# Metadata for each Church Father author ID found in the ANF corpus.
# floruit: approximate year of peak activity (CE).
# century: century of activity for era-based queries.
# display_name: human-readable name.
# Note: "editors" are 19th-century editorial contributors, not Church Fathers.
AUTHOR_METADATA: dict[str, dict[str, object]] = {
    "alexander_alexandria": {
        "display_name": "Alexander of Alexandria",
        "floruit": 313,
        "century": 4,
        "is_editor": False,
    },
    "alexander_capp": {
        "display_name": "Alexander of Cappadocia",
        "floruit": 215,
        "century": 3,
        "is_editor": False,
    },
    "alexander_lyc": {
        "display_name": "Alexander of Lycopolis",
        "floruit": 300,
        "century": 4,
        "is_editor": False,
    },
    "anatolius": {
        "display_name": "Anatolius of Laodicea",
        "floruit": 270,
        "century": 3,
        "is_editor": False,
    },
    "anonymous": {
        "display_name": "Anonymous",
        "floruit": None,
        "century": None,
        "is_editor": False,
    },
    "archelaus": {
        "display_name": "Archelaus",
        "floruit": 277,
        "century": 3,
        "is_editor": False,
    },
    "aristides": {
        "display_name": "Aristides of Athens",
        "floruit": 125,
        "century": 2,
        "is_editor": False,
    },
    "arnobius": {
        "display_name": "Arnobius of Sicca",
        "floruit": 305,
        "century": 4,
        "is_editor": False,
    },
    "asterius": {
        "display_name": "Asterius of Amasea",
        "floruit": 341,
        "century": 4,
        "is_editor": False,
    },
    "athenagoras": {
        "display_name": "Athenagoras of Athens",
        "floruit": 177,
        "century": 2,
        "is_editor": False,
    },
    "caius": {
        "display_name": "Caius of Rome",
        "floruit": 200,
        "century": 3,
        "is_editor": False,
    },
    "clement_alex": {
        "display_name": "Clement of Alexandria",
        "floruit": 215,
        "century": 3,
        "is_editor": False,
    },
    "clement_rome": {
        "display_name": "Clement of Rome",
        "floruit": 96,
        "century": 1,
        "is_editor": False,
    },
    "commodianus": {
        "display_name": "Commodianus",
        "floruit": 240,
        "century": 3,
        "is_editor": False,
    },
    "cyprian": {
        "display_name": "Cyprian of Carthage",
        "floruit": 258,
        "century": 3,
        "is_editor": False,
    },
    "dionysius": {
        "display_name": "Dionysius of Alexandria",
        "floruit": 265,
        "century": 3,
        "is_editor": False,
    },
    "felix": {
        "display_name": "Minucius Felix",
        "floruit": 200,
        "century": 3,
        "is_editor": False,
    },
    "gregory_thau": {
        "display_name": "Gregory Thaumaturgus",
        "floruit": 270,
        "century": 3,
        "is_editor": False,
    },
    "hermas": {
        "display_name": "Hermas",
        "floruit": 150,
        "century": 2,
        "is_editor": False,
    },
    "hippolytus": {
        "display_name": "Hippolytus of Rome",
        "floruit": 236,
        "century": 3,
        "is_editor": False,
    },
    "ignatius": {
        "display_name": "Ignatius of Antioch",
        "floruit": 107,
        "century": 2,
        "is_editor": False,
    },
    "juliusafricanus": {
        "display_name": "Julius Africanus",
        "floruit": 240,
        "century": 3,
        "is_editor": False,
    },
    "justin_martyr": {
        "display_name": "Justin Martyr",
        "floruit": 165,
        "century": 2,
        "is_editor": False,
    },
    "lactantius": {
        "display_name": "Lactantius",
        "floruit": 320,
        "century": 4,
        "is_editor": False,
    },
    "malchion": {
        "display_name": "Malchion",
        "floruit": 268,
        "century": 3,
        "is_editor": False,
    },
    "mathetes": {
        "display_name": "Mathetes (Epistle to Diognetus)",
        "floruit": 130,
        "century": 2,
        "is_editor": False,
    },
    "methodius": {
        "display_name": "Methodius of Olympus",
        "floruit": 311,
        "century": 4,
        "is_editor": False,
    },
    "novatian": {
        "display_name": "Novatian",
        "floruit": 258,
        "century": 3,
        "is_editor": False,
    },
    "origen": {
        "display_name": "Origen of Alexandria",
        "floruit": 254,
        "century": 3,
        "is_editor": False,
    },
    "peter_alexandria": {
        "display_name": "Peter of Alexandria",
        "floruit": 311,
        "century": 4,
        "is_editor": False,
    },
    "phileas": {
        "display_name": "Phileas of Thmuis",
        "floruit": 307,
        "century": 4,
        "is_editor": False,
    },
    "pierus": {
        "display_name": "Pierius of Alexandria",
        "floruit": 309,
        "century": 4,
        "is_editor": False,
    },
    "polycarp": {
        "display_name": "Polycarp of Smyrna",
        "floruit": 155,
        "century": 2,
        "is_editor": False,
    },
    "rutherford_an": {
        "display_name": "Rutherford (editor)",
        "floruit": None,
        "century": None,
        "is_editor": True,
    },
    "schaff": {
        "display_name": "Philip Schaff (editor)",
        "floruit": None,
        "century": None,
        "is_editor": True,
    },
    "tatian": {
        "display_name": "Tatian the Syrian",
        "floruit": 170,
        "century": 2,
        "is_editor": False,
    },
    "tertullian": {
        "display_name": "Tertullian",
        "floruit": 220,
        "century": 3,
        "is_editor": False,
    },
    "theodotus": {
        "display_name": "Theodotus",
        "floruit": 200,
        "century": 3,
        "is_editor": False,
    },
    "theognostus": {
        "display_name": "Theognostus",
        "floruit": 282,
        "century": 3,
        "is_editor": False,
    },
    "theonas": {
        "display_name": "Theonas of Alexandria",
        "floruit": 300,
        "century": 4,
        "is_editor": False,
    },
    "theophilus": {
        "display_name": "Theophilus of Antioch",
        "floruit": 180,
        "century": 2,
        "is_editor": False,
    },
    "venantius": {
        "display_name": "Venantius",
        "floruit": 290,
        "century": 3,
        "is_editor": False,
    },
    "victorinus": {
        "display_name": "Victorinus of Pettau",
        "floruit": 304,
        "century": 4,
        "is_editor": False,
    },
}
