import type { AuthorRow, BookRow, PsalmRow, Summary, VolumeComparisonRow } from "./types";

// These imports are resolved at build time from the JSON files generated by the pipeline.
// Run `python data_processer.py` before `npm run build`.
import summaryData from "../data/summary.json";
import booksData from "../data/books.json";
import authorsData from "../data/authors.json";
import psalmsData from "../data/psalms.json";
import volumeComparisonData from "../data/volume_comparison.json";

export function getSummary(): Summary {
  return summaryData as Summary;
}

export function getBooks(): BookRow[] {
  return booksData as BookRow[];
}

export function getAuthors(): AuthorRow[] {
  return authorsData as AuthorRow[];
}

export function getPsalms(): PsalmRow[] {
  return psalmsData as PsalmRow[];
}

export function getVolumeComparison(): VolumeComparisonRow[] {
  return volumeComparisonData as VolumeComparisonRow[];
}

export function getTestamentLabel(group: string): string {
  switch (group) {
    case "new_testament":
      return "New Testament";
    case "deuterocanonical":
      return "Deuterocanonical";
    default:
      return "Old Testament";
  }
}

export function getCenturyLabel(century: number | null): string {
  if (century === null) return "Unknown";
  const suffixes: Record<number, string> = { 1: "st", 2: "nd", 3: "rd", 4: "th" };
  return `${century}${suffixes[century] ?? "th"} century`;
}
